server:
  port: 2023
spring:
  application:
    name: rh-service
  datasource:
    password: w@2915djkq#
    url: jdbc:mysql://localhost:3306/rh-service?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect